### PR TITLE
add property failOnMissingReportFile to skip modules w/o an report file

### PR DESCRIPTION
**Pull request by adlerre**

### CODE REVIEW

**Comment by halkeye** [comment]
Oh cool

What happens of you make the type a boolean?

**Comment by adlerre** [comment]
We haven an multi-module maven project and configured the coverage reporting within parent pom.xml. But not all modules generates a report and so we need a possibility to skip/ignore modules without a report file.

**Comment by halkeye** [comment]
oh totally up for doing the merge

I just figured maven would auto convert true/false to a boolean if you made the variable type boolean instead of string.

**Comment by adlerre** [comment]
Oh, sorry. I don't read the manual. ;)

**Comment by halkeye** [comment]
Thanks for the contribution

1.0.3 was pushed

**Pull request merged**
