### PR TITLE
Bump versions for Codacy dependencies

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Updated Codacy artifacts to recent versions.

### CODE REVIEW

**Comment by halkeye** [comment]
thanks for this. I havn't really been doing java lately. 

Any ideas why the tests are not working?

**Comment by JWGmeligMeyling** [comment]
The plugin works fine (I released my fork locally), but the tests fail locally too. I suppose it is API related, perhaps the API key for the test env has expired. Ill dive deeper into the failing tests tomorrow.

**Comment by halkeye** [comment]
I think I got most of the tests working. I'll push a pr to your branch sometime tomorrow (bug me if i don't).

**Comment by halkeye** [comment]
okay thanks for this. I merged everything manually. 🤞

**Comment by JWGmeligMeyling** [comment]
Thanks!

**Pull request merged**
